path/src/Ws/EventsBundle/Entity/Search.php
<?php

namespace Ws\EventsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Events;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

use My\WorldBundle\Entity\Country;
use My\WorldBundle\Entity\City;
use My\UserBundle\Entity\User;
use My\WorldBundle\Entity\Location;
use Ws\EventsBundle\Entity\Event;
use Ws\SportsBundle\Entity\Sport;

/**
 * Search
 *
 * @ORM\Table(name="events_search")
 * @ORM\Entity(repositoryClass="Ws\EventsBundle\Repository\AlertRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Search
{    
    /**
     * @ORM\Id @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @ORM\Column(name="date_created", type="datetime")
    */
    private $date_created = null;

     /**
    * @ORM\ManyToOne(targetEntity="My\UserBundle\Entity\User")
    * @ORM\JoinColumn(name="user_id", nullable=true, onDelete="SET NULL")
    */
    private $user = null;

    /**
    * @ORM\Column(name="date", type="string", nullable=true)
    */
    private $date = null;

    /**
    * @ORM\ManyToOne(targetEntity="My\WorldBundle\Entity\Location", fetch="EAGER")
    * @ORM\JoinColumn(name="location_id", nullable=true)
    */
    private $location = null;

    /**
    * @ORM\Column(name="area_distance", type="integer", nullable=true)
    */
    private $area = null;

    /**
    * @ORM\ManyToMany(targetEntity="Ws\SportsBundle\Entity\Sport", inversedBy="searchs", cascade={"persist"})
    */
    private $sports = null;

    /**
    * @ORM\Column(name="nb_days", type="integer", nullable=true)
    */
    private $nb_days = null;

    /**
    * @ORM\Column(name="day_of_week", type="string", nullable=true)
    */
    private $day_of_week = array();

    /**
    * @ORM\Column(name="type", type="string")
    */
    private $type = array();

    /**
    * @ORM\Column(name="timestart", type="datetime", nullable=true)
    */
    private $timestart = null;

    /**
    * @ORM\Column(name="timeend", type="datetime", nullable=true)
    */
    private $timeend = null;

    /**
    * @ORM\Column(name="price", type="integer", nullable=true)
    */
    private $price = null;

    /**
    * @ORM\Column(name="level", type="string")
    */
    private $level = array();

    /**
    * @ORM\Column(name="ordered", type="string")
    */
    private $ordered;

    /**
    * @ORM\Column(name="visibility", type="string")
    */
    private $visibility;

    /**
    * @ORM\ManyToOne(targetEntity="My\UserBundle\Entity\User", inversedBy="searched")
    * @ORM\JoinColumn(name="organizer_id", nullable=true)
    */
    private $organizer = null;

    public $country; 

    public $url = null;
    public $url_params = null;
    public $short_url_params = null;
    private $default = array( //usefull ?
        'day_of_week' => array('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),
        );

    public function __construct()
    {
        //set defaults
        //$this->sports = new \Doctrine\Common\Collections\ArrayCollection();
        $this->level = array(); //"all level"
        $this->date = \date('Y-m-d');
        $this->nb_days = 7;
        $this->ordered = 'chronological';
        $this->visibility = 'public';
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function onPrePersist()
    {
        if(is_array($this->type)) $this->type = json_encode($this->type, JSON_FORCE_OBJECT);
        if(is_array($this->level)) $this->level = json_encode($this->level, JSON_FORCE_OBJECT);
        if(is_array($this->day_of_week)) $this->day_of_week = json_encode($this->day_of_week, JSON_FORCE_OBJECT);
        $this->date_created = new \DateTime();
    }

    /**
     * @ORM\PostLoad
     */
    public function onPostLoad()
    {;
        $this->type = json_decode($this->type, JSON_FORCE_OBJECT);
        $this->level = json_decode($this->level, JSON_FORCE_OBJECT);
        $this->day_of_week = json_decode($this->day_of_week, JSON_FORCE_OBJECT);
    }

    public function getValues()
    {
        return array(
            'location' => $this->getLocation(),
            'area' => $this->getArea(),
            'sports' => $this->getSports(),
            'nb_days' => $this->getNbDays(),
            'day_of_week' => $this->getDayOfWeek(),
            'type' => $this->getType(),
            'time' => $this->getTime(),
            'price' => $this->getPrice(),
            'level' => $this->getLevel(),
            'country' => $this->getCountry(),
            'timestart' => $this->getTimeStart(),
            'timeend' => $this->getTimeEnd()
            );
    }

    public function getHtmlLocationString()
    {
        $html = '';
        if($this->hasLocation()){
            $html = '<strong>'.$this->location->getCity()->getName();
            if($this->area != null) $html .= ' +'.$this->area.'km';
            $html .= '</strong> ';
            $html .= '<span>('.$this->location->getLastState()->getName().', ';
            $html .= $this->location->getCountry()->getName().')</span>';
        }

        return $html;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function hasDate()
    {
        if(isset($this->date) && $this->date != 'none') return true;
        return false;
    }
    public function setDate($date)
    {
        $this->date = $date;
    }

    public function setUser(User $user)
    {
    	$this->user = $user;
    	return $this;
    }

    public function getUser()
    {
    	return $this->user;
    }

    public function setAlert(Alert $alert)
    {
        $this->alert = $alert;
    }

    public function getAlert()
    {
        return $this->alert;
    }

    public function hasAlert()
    {
        if(isset($this->alert)) return true;
        return false;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function hasCountry()
    {
        if(isset($this->country)) return true;
        return false;
    }

    public function setCountry(Country $country)
    {
        $this->country = $country;
    }

    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        if(isset($this->location) && $this->location->getId() != null) return true;
        return false;
    }

    public function setLocation(Location $location)
    {
        $this->location = $location;
        return $this;
    }

    public function getArea()
    {
        return $this->area;
    }

    public function hasArea()
    {
        if(isset($this->area) && $this->area != 0) return true;
        return false;
    }

    public function setArea($area)
    {
        $this->area = (int) $area;
    }

    public function getSports()
    {
        return $this->sports;
    }

    public function getSportsArrayIds()
    {
        $a = array();
        foreach ($this->sports as $k => $sport) {
            if($sport instanceof Sport) $a[] = $sport->getId();
            else unset($this->sports[$k]);
        }
        return $a;
    }

    public function addSport($sport)
    {
        $this->sports[] = $sport;
    }

    public function hasSports()
    {
        return !empty($this->sports);
    }    

    public function setSports($sports)
    {
        $this->sports = $sports;
    }

    public function getNbDays()
    {
        return $this->nb_days;
    }

    public function hasNbDays()
    {
        if(isset($this->nb_days) && $this->nb_days != 0) return $this->nb_days;
        return false;
    }

    public function setNbDays($nb)
    {
        $this->nb_days = (int) $nb;
    }

    public function getType()
    {
        return $this->type;
    }

    public function getTypeNames()
    {
        return array_map(function($n){ return Event::$valuesAvailable['type'][$n]; },$this->type);
    }

    public function getTypeKeys()
    {
        return array_keys($this->type);
    }

    public function hasType()
    {
        if(is_array($this->type) && !empty($this->type) && count($this->type) != count(Event::$valuesAvailable['type'])) return true;
        return false;
    }

    public function setType($type)
    {
        $this->type = $type;
    }

    public function getDayOfWeek()
    {
        return $this->day_of_week;
    }

    public function hasDayOfWeek()
    {
        if(!empty($this->day_of_week)) return true;
        return false;
    }

    public function setDayOfWeek($days)
    {
        $this->day_of_week = $days;
    }

    public function getTime($w = null)
    {
        return array('start'=>$this->timestart,'end'=>$this->timeend);

    }

    public function hasTime($t = null)
    {
        if($t=='start' && isset($this->timestart)) return true;
        if($t=='end' && isset($this->timeend)) return true;
        if($t==null && ( isset($this->timestart) || isset($this->timeend) ) ) return true;
        return false;       
    }

    public function getTimeStart()
    {
        return $this->timestart;
    }

    public function hasTimeStart()
    {
        if(isset($this->timestart)) return true;
        return false;
    }

    public function setTimeStart(\Datetime $datetime)
    {
        $this->timestart = $datetime;
    }

    public function getTimeEnd()
    {
        return $this->timeend;
    }

    public function hasTimeEnd()
    {
        if(isset($this->timeend)) return true;
        return false;
    }

    public function setTimeEnd(\Datetime $datetime)
    {
        $this->timeend = $datetime;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function hasPrice()
    {
        if(isset($this->price)) return true;
        return false;
    }

    public function setPrice($price)
    {
        $this->price = $price;
    }

path/src/Ws/EventsBundle/Form/Type/AlertType.php
<?php
namespace Ws\EventsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use My\WorldBundle\Form\Type\AutoCompleteCityType;
use Ws\SportsBundle\Form\Type\SelectSportType;
use Ws\EventsBundle\Manager\CalendarManager;
use Ws\EventsBundle\Form\Type\SerieType;
use Ws\EventsBundle\Form\Type\CalendarSearchType;
use My\UserBundle\Entity\User;

class AlertType extends AbstractType
{

    private $user;

    public function __construct(SecurityContext $secu)
    {
        $this->user = $secu->getToken()->getUser();
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email','text',array(
                'required' => true,
                ))
            ->add('frequency','choice',array(
                'choices'=>array('daily'=>'daily','weekly'=>'weekly'),
                'expanded'=> false,
                'multiple'=> false,
                'required'=> true,
                'empty_data' => 'daily',  
                'translation_domain' => 'WsEventsBundle_alert',              
                ))
            ->add('duration','choice',array(
                'label'=>"Pour combien de temps",
                'choices'=>array(1=>"1 mois",2=>"2 mois",3=>"3 mois",6=>"6 mois",12 =>"1 an"),
                'expanded'=> false,
                'multiple'=> false,
                'required'=> true,
                'empty_data'=> 3,
                ))
            ->add('search','calendar_search')
            ;
    		
            $builder->addEventListener(FormEvents::PRE_SET_DATA, array($this, 'onPreSetData'));
            $builder->addEventListener(FormEvents::POST_SUBMIT, array($this, 'onPostSubmit'));
    }

    public function onPreSetData(FormEvent $event)
    {
        $form = $event->getForm();

        if($this->user instanceof User){

            $form->add('email','text',array(
                'required' => true,
                'mapped' => true,
                'data' => $this->user->getEmail()
                ));
        }        
    }

     public function onPostSubmit(FormEvent $event)
    {
        $form = $event->getForm();
        $alert = $event->getData();

        if( $this->user instanceof User) {
            //Set the current user 
            $alert->setUser($this->user);
            
        }

    }
    public function getName()
    {
        return 'alert';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
	    $resolver->setDefaults(array(
            'invalid_message' => "Oups, ça s'était pas prévu, il y a une erreur dans le formulaire...",
	        'data_class' => 'Ws\EventsBundle\Entity\Alert',
            'cascade_validation' => true,
	    ));
	}
}

?>

path/src/Ws/EventsBundle/Resources/views/Alert/Blocks/row_alert.html.twig
<tr class="row-alert {% if alert.active %}row-alert-active{% else %}row-alert-pending{% endif %}">
	<td class="cell-status">
		{% if alert.active %}
			<span class="ws-icon ws-icon-checkmark-circle"></span>
			En&nbsp;cours
		{% else %}
			<span class="ws-icon ws-icon-blocked"></span>
			Stopé
		{% endif %}		
	</td>

	<td class="cell-resume">										
		{% include 'WsEventsBundle:Alert:Blocks/tx_resume.html.twig' %}							
	</td>

	<td class="cell-frequency">										
		{% include 'WsEventsBundle:Alert:Blocks/tx_frequency.html.twig' %}							
	</td>
	
	<td class='cell-action'>
		<p><a class="btn btn-mini" href="{{ path('ws_alerts_delete',{alert:alert.id}) }}">Supprimer</a></p>	

		{% if alert.active %}
			<p><a class="btn btn-mini" href="{{ path('ws_alerts_disable',{alert:alert.id}) }}">Désactiver</a></p>
		{% else %}
			<p><a class="btn btn-mini" href="{{ path('ws_alerts_enable',{alert:alert.id}) }}">Réactiver</a></p>
		{% endif %}

		<p><a class="btn btn-mini" href="{{ path('ws_alerts_extend',{alert:alert.id,nbmonth:3}) }}">Prolonger</a></p>

		<p><a class="btn btn-mini" href="{{ path('ws_alerts_view',{alert:alert.id}) }}">Voir les activités</a></p>			
	</td>
</tr>

path/src/Ws/EventsBundle/Resources/views/Alert/Blocks/tx_frequency.html.twig
		{# tout les jours | une fois par semaine #}
		<span><strong>{{ (alert.frequency)|trans({},'WsEventsBundle_alert')|capitalize }}</strong></span>		

		{# jusqu'au 14 septembre #}
		<span> jusqu'au <strong>{{ alert.dateStop | localizeddate('long','none') }}</strong></span>

		{# à l'adresse email #}
		<span> à l'adresse <strong>{{ alert.email }}</strong></span>

path/src/Ws/EventsBundle/Resources/views/Alert/Blocks/tx_resume.html.twig
		{# Les annonces de #}
		<span>Les annonces </span>
		
		{# Football Volley Kayak #}
		{% if alert.search.sports is not empty %}
			<span> des sports 
			{% for sport in alert.search.sports %}
				<strong> {{ sport.name}} </strong>
			{% endfor %}
			</span>
		{% endif %}
		
		{# à Montpellier #}
		{% if alert.search.location %}<span>à <strong>{{ alert.search.location.city.name }}</strong></span>{% endif %}

		{# étendu de 50km #}
		{% if alert.search.area %}<span> étendu de <strong>{{ alert.search.area }}km</strong></span>{% endif %}

		{# de niveau débutant #}
		{% if alert.search.hasLevel %}<span> de niveaux <strong>{% for level in alert.search.level %} {{ level|trans({},'WsEventsBundle_event') }} {% endfor %}</strong></span>{% endif %}

		{# organisé par #}
		{% if alert.search.hasType %}<span> organisé par les<strong>{% for type in alert.search.type %} {{ ('user.types.'~type)|trans({},'MyUserBundle') }} {% endfor %}</strong></span>{% endif %}

		{# d'un prix inférieur à #}
		{% if alert.search.price %}<span> d'un prix inférieur à <strong>{{ alert.search.price }}€</strong></span>{% endif %}

		{# les lundi mardi jeudi #}
		{% if alert.search.hasDayOfWeek %}<span> les <strong>{% for day in alert.search.dayOfWeek %} {{ ('days.day.'~day|lower)|trans({},'MyUtilsBundle') }}, {% endfor %}</strong></span>{% endif %}

		{# entre 10h et 14h #}
		{% if alert.search.hasTimeStart and alert.search.hasTimeEnd %}<span> entre <strong>{{ alert.search.timeStart|date('H\\hi') }}</strong></span> et <strong>{{ alert.search.timeEnd|date('H\\hi') }}</strong></span> 
		{% else %}
			{% if alert.search.hasTimeStart %}<span> aprés <strong>{{ alert.search.timeStart|date('H\\hi') }}</strong></span> {% endif %}
			{% if alert.search.hasTimeEnd %}<span> aprés <strong>{{ alert.search.timeEnd|date('H\\hi') }}</strong></span> {% endif %}
		{% endif %}

		{# de Organisateur #}
		{% if alert.search.organizer %}<span> de l'utilisateur <strong><a href="{{ alert.search.organizer|link2user }}">{{ alert.search.organizer.username|capitalize }}</a><strong></span>{% endif %}